---

# Configure the service's launch options.
- include_tasks: "service_config_{{ ansible_os_family }}.yml"

# Install all OS packages (including Jenkins itself).
- include_tasks: "packages_{{ ansible_os_family }}.yml"

- name: Create Jenkins Init Script Directory
  # Reference: https://wiki.jenkins-ci.org/display/JENKINS/Post-initialization+script
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  become: true

# Enable the Jenkins CLI.
- import_tasks: "cli_config.yml"

# Install and/or update plugins.
- import_tasks: "plugins.yml"

- name: Configure Jenkins (Miscellaneous Settings)
  shell:
    cmd: |
      cat <<EOF |
      // These are the basic imports that Jenkin's interactive script console
      // automatically includes.
      import jenkins.*;
      import jenkins.model.*;
      import hudson.*;
      import hudson.model.*;

      // Enable Jenkins' slave agent port, because most everyone will want it.
      // This will use a setter, which will set the value (to a random port)
      // and also initialize the slave agent.
      if (Jenkins.instance.slaveAgentPort != 0) {
        Jenkins.instance.slaveAgentPort=0
        println "Changed slave agent configuration."
      }

      // Set the Jenkins external URL, if defined.
      // (Hat tip: http://stackoverflow.com/questions/30355079/jenkins-setting-root-url-via-groovy-api.)
      def externalUrl = "{{ '' if jenkins_url_external == None else (jenkins_url_external | default('') | trim) }}"
      def locationConfig = JenkinsLocationConfiguration.get()
      println("Configuring Jenkins External URL (current URL: '\${locationConfig.url}')...")
      if (!externalUrl.equals(locationConfig.url)) {
        locationConfig.url = externalUrl
        locationConfig.save()
        println "Changed external URL"
      }
      EOF
      {{ jenkins_cli_command }} groovy =
  become: true
  become_user: jenkins
  register: shell_jenkins_config_misc
  changed_when: "(shell_jenkins_config_misc | success) and 'Changed' not in shell_jenkins_config_misc.stdout"

# Fire any pending restart handlers now, or else the tests below here may not
# be valid.
- meta: flush_handlers

- name: Ensure Service 'jenkins' Is Running
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: Grab Jenkins Web UI Content
  # By default, Jenkins 2 is set to require auth, so the only page we can grab 
  # without getting a 403 and redirect is the login page.
  uri:
    url: "http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }}/login"
    return_content: true
  register: jenkins_ui

- name: Verify Jenkins Web UI Content
  action: fail
  when: jenkins_ui.content.find('Jenkins ver. 2') == -1
