---

# Install all OS packages (including Jenkins itself).
- include: "packages_{{ ansible_os_family }}.yml"

# Configure the service's launch options.
- include: "service_config_{{ ansible_os_family }}.yml"

# Enable the Jenkins CLI.
- include: "cli_config.yml"

- name: Ensure Service 'jenkins' Is Running
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: Grab Jenkins Web UI Content
  uri:
    url: "http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }}"
  register: jenkins_ui

- name: Verify Jenkins Web UI Content
  action: fail
  when: "'Jenkins ver. 2.0-rc-1' not in jenkins_ui.content"
