---
- name: Determine YUM Repo to Use
  set_fact:
    jenkins_yum_repo_name: "{{ 'Jenkins' if jenkins_release_line == 'weekly' else 'Jenkins-stable' }}"
    jenkins_yum_repo_baseurl: "{{ 'https://pkg.jenkins.io/redhat' if jenkins_release_line == 'weekly' else 'http://pkg.jenkins.io/redhat-stable' }}"
    jenkins_yum_repo_gpgkey: "{{ 'https://pkg.jenkins.io/redhat/jenkins.io.key' if jenkins_release_line == 'weekly' else 'https://pkg.jenkins.io/redhat-stable/jenkins.io.key' }}"

- name: Remove Unused Jenkins YUM Repositories
  yum_repository:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
    - 'Jenkins'
    - 'Jenkins-stable'
  when: "item != jenkins_yum_repo_name"

- name: Add Jenkins YUM Repository
  yum_repository:
    name: "{{ jenkins_yum_repo_name }}"
    description: 'Jenkins release repo from https://jenkins.io/download/.'
    baseurl: "{{ jenkins_yum_repo_baseurl }}"
    gpgcheck: true
    gpgkey: "{{ jenkins_yum_repo_gpgkey }}"
    state: present
  become: true

- name: Jenkins Install
  yum:
    name: jenkins
    # Setting this to 'latest' is perhaps debatable, but it seems silly not to
    # since this plugin also updates all of the Jenkins plugins automatically.
    state: latest
  become: true

- name: Configure Jenkins Launch Settings
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    mode: u=rw,g=,o=r
  become: true
  with_items:
    - regexp: '^JENKINS_JAVA_OPTIONS='
      # Note: The setup wizard has to be disabled before Jenkins runs the first
      # time. Fortunately, the RHEL packages don't automatically start the
      # Jenkins service after install, so we have time to address this.
      line: "JENKINS_JAVA_OPTIONS=\"-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false {{ jenkins_java_args_extra }}\""
    - regexp: '^JENKINS_PORT='
      line: "JENKINS_PORT={{ jenkins_port }}"
  notify:
    - "Restart Service 'jenkins'"
