---
##
# Installs and verifies Jenkins on the container being used for the test case. 
##

# Install an Oracle 8 JRE.
- hosts: docker_container
  # The "geerlingguy.java" role requires this, but doesn't declare it.
  become: true
  vars:
    java_packages: ["oracle-java8-installer"]
  roles:
    - geerlingguy.java

# Install Jenkins.
- hosts: docker_container
  roles:
    - karlmdavis.jenkins2

# Run some test cases to verify that Jenkins is running as expected.
- include: basic_test_verify.yml
