---
##
# Installs and verifies Jenkins on the container being used for the test case. 
##

# Install Java 8.
- include: "install_java_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"

# Install Jenkins.
- hosts: docker_container
  roles:
    - karlmdavis.jenkins2

# Run some test cases to verify that Jenkins is running as expected.
- include: basic_test_verify.yml
